# Generated by Django 4.2.1 on 2023-06-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('detalle', models.CharField(max_length=30)),
                ('nivel', models.CharField(max_length=30)),
                ('fkcategoria', models.CharField(choices=[('GEN', 'General'), ('PRE', 'Ciclo Preescolar'), ('BAS', 'Ciclo Basico'), ('MED', 'Ciclo Medio')], max_length=3)),
                ('fecha_envio', models.DateField()),
                ('fecha_ultima', models.DateField()),
            ],
        ),
    ]
