# Generated by Django 4.2.1 on 2023-06-02 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_docente_comunicado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='comunicado',
            name='detalle',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='comunicado',
            name='nivel',
            field=models.CharField(choices=[('GEN', 'General'), ('PRE', 'Ciclo Preescolar'), ('BAS', 'Ciclo Basico'), ('MED', 'Ciclo Medio')], max_length=3),
        ),
        migrations.AlterField(
            model_name='comunicado',
            name='fkcategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria'),
        ),
    ]
